name: Build Vanilla Music APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up JDK 11
      uses: actions/setup-java@main
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Fixed Debug APK
      run: ./gradlew assembleDebug -Pandroid.injected.signing.store.file=$(pwd)/release.keystore -Pandroid.injected.signing.store.password=android -Pandroid.injected.signing.key.alias=release -Pandroid.injected.signing.key.password=android

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vanilla-music-custom-apk
        path: app/build/outputs/apk/debug/*.apk
